added win ps5.1

diff --git a/.github/workflows/Pester_all_os.yml b/.github/workflows/Pester_all_os.yml
--- a/.github/workflows/Pester_all_os.yml
+++ b/.github/workflows/Pester_all_os.yml
@@ -6,7 +6,10 @@ on:
       - v2.1
   pull_request:
     branches:
-      - v2.1-some
+      - v2.1
+
+env:
+  GH_PROJECTNAME: PSLiteDB
 
 jobs:
   job-1-pwsh:
@@ -14,29 +17,18 @@ jobs:
       matrix:
         platform: [ubuntu-latest, macos-latest, windows-latest]
     runs-on: ${{ matrix.platform }}
-
     steps:
-      - name: Checkout repository
+      - name: Step-1 Clone Repository
         uses: actions/checkout@v2.3.1
 
-      - name: Set environment variables
+      - name: Step-2 Run Pester Tests via pwsh
         run: |
-          $Username, $ProjectName = $env:GITHUB_REPOSITORY -split "/"
-          @(
-            "GH_USERNAME={0}" -f $Username
-            "GH_PROJECTNAME={0}" -f $ProjectName
-          ) | Add-Content -Path $env:GITHUB_ENV
-        shell: pwsh
-
-
-      - name: Run Pester Tests
-        run: |
-          Import-Module (join-path $env:GITHUB_WORKSPACE -childpath 'module/PSLiteDB.psd1')
+          Import-Module (join-path $env:GITHUB_WORKSPACE -childpath ('module/{0}.psd1' -f $env:GH_PROJECTNAME))
           Invoke-Pester -path (join-path $env:GITHUB_WORKSPACE -childpath 'tests/v5.tests.ps1') -pass -Outputfile pester_test_result.xml -OutputFormat NUnitXml
         shell: pwsh
 
-      - name: test module
-        id: test_module
+      - name: Step-3 Create Pester Reports
+        id: $env:GH_PROJECTNAME
         uses: zyborg/pester-tests-report@v1
         with:
           test_results_path: pester_test_result.xml
@@ -45,3 +37,28 @@ jobs:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           gist_token: ${{ secrets.GIST_TOKEN }}
           gist_name: ${{ runner.os }}
+
+  job-2-powershell5:
+    runs-on: windows-latest
+    steps:
+      - name: Step-1 Clone Repository
+      - uses: actions/checkout@v2
+
+      - name: Step-2 Run Pester tests (Windows PowerShell 5.1)
+        run: |
+          Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor
+          Import-Module (join-path $env:GITHUB_WORKSPACE -childpath ('module/{0}.psd1' -f $env:GH_PROJECTNAME))
+          Invoke-Pester -path (join-path $env:GITHUB_WORKSPACE -childpath 'tests/v5.tests.ps1') -pass -Outputfile pester_test_result.xml -OutputFormat NUnitXml
+          if ($Error[0].Fullyqualifiederrorid -eq 'PesterAssertionFailed') {exit 1}
+        shell: powershell
+
+      - name: Step-3 Create Pester Reports
+        id: $env:GH_PROJECTNAME
+        uses: zyborg/pester-tests-report@v1
+        with:
+          test_results_path: pester_test_result.xml
+          report_name: WinPS5.1 ${{ runner.os }}
+          report_title: Pester Results on ${{ runner.os }} using Windows PowerShell 5.1
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          gist_token: ${{ secrets.GIST_TOKEN }}
+          gist_name: WinPS5.1 ${{ runner.os }}
